apiVersion: v1
kind: Service
metadata:
  name: joomla
spec:
  selector:
    app: joomla
    tier: frontend
  type: LoadBalancer
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla
  labels:
    app: joomla
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: joomla
      tier: frontend
  template:
    metadata:
      name: joomla
      labels:
        app: joomla
        tier: frontend
    spec:
      containers:
      - name: joomla
        image: joomla:latest
        env:
        - name: JOOMLA_DB_HOST
          value: joomla-mysql
        - name: JOOMLA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: JOOMLA_DB_NAME
          value: joomladb             
        ports:
        - containerPort: 80
          name: joomla
        volumeMounts:
        - name: joomla-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: joomla-persistent-storage
        persistentVolumeClaim:
          claimName: efs-joomla
