apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=ishver
resources:
  # - efs-provisioner.yaml
  # - rbac.yaml
  - storage.yaml
  - mysql.yaml
  - joomla.yaml



